---
title: "Preparation for Homework 02"
author: "Renato Albolea"
date: "4/28/2020"
output: 
  html_document: 
    keep_md: yes
    toc: yes
    toc_float: true
    toc_depth: 4
    code_download: yes

---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 

# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), 
                                                    detach, character.only = TRUE, unload = TRUE)
# Load lpSolve package to demonstrate simple LP
library(lpSolveAPI)
`%>%` <- magrittr::`%>%`
library(knitr)
library(kableExtra)

```

```{r}
# Course: 5260 Math models for decision making
# Title: Preparation for Homework #2 
# Date: April 28th, 2020
# Author: Renato Albolea

```


```{r echo = FALSE}

sensitivity_table <- function(model){
  # Make solution/sensitivity analysis table
  # Get primal solution
  ps <- get.primal.solution(model)
  
  
  # Get sensitivity analysis
  obj_sa <- get.sensitivity.obj(model)
  rhs_sa <- get.sensitivity.rhs(model)
  
  n <- length(get.variables(model))
  m <- length(get.constr.type(model))
  ov <- paste0("Objective Value = ", ps[1])
  
  sa_tab <- rbind(ps[2:(n + m + 1)], 
                  c(round(rhs_sa$duals[1:m], 2), obj_fn),
                  round(c(rhs_sa$dualsfrom[1:m],obj_sa$objfrom), 2),
                  round(c(rhs_sa$dualstill[1:m],obj_sa$objtill), 2)) 
  colnames(sa_tab) <- c(rownames(model), colnames(model))
  rownames(sa_tab) <- c("solution", "duals/coef", "Sens From", "Sens Till")      
  
  # Substitute "inf" and "-inf" so tables are easier to read (coded by two classmates!)
  sa_tab <- ifelse(sa_tab == -1.000e+30, "-inf", sa_tab)
  sa_tab <- ifelse(sa_tab == 1.000e+30, "inf", sa_tab)
  
  # Print the table
  kable(sa_tab, format.args = list(big.mark = ",")) %>%
    kable_styling(bootstrap_options = c("striped", "bordered")) %>% 
    add_footnote(label = ov, notation = "none")
}

  
```

# Problem 9.1-2  The Childfair Company

#### a. Formulate a linear programming model algebraically  

  
####   b. Set up and solve in R.  



```{r}

# Set up the cost minimization
trans_9_2 <- make.lp(0, 12)

# Build objective function and constraints
obj_fn <- c(100+800*0.5, 100+1300*0.5, 100+400*0.5, 100+700*0.5, 100+1100*0.5, 100+1400*0.5, 100+600*0.5, 100+1000*0.5, 100+600*0.5, 100+1200*0.5, 100+800*0.5, 100+900*0.5)
set.objfn(trans_9_2, obj_fn)

# Distribution Constraint
add.constraint(trans_9_2, c(rep(c(1, 0, 0, 0),3)), "=", 10)
add.constraint(trans_9_2, c(rep(c(0, 1, 0, 0),3)), "=", 10)
add.constraint(trans_9_2, c(rep(c(0, 0, 1, 0),3)), "=", 10)
add.constraint(trans_9_2, c(rep(c(0, 0, 0, 1),3)), "=", 10)

# Plant Constraint
add.constraint(trans_9_2, c(rep(1, 4), rep(0, 8)), "<=", 12)
add.constraint(trans_9_2, c(rep(0, 4),rep(1, 4), rep(0, 4)), "<=", 17)
add.constraint(trans_9_2, c(rep(0, 8),rep(1, 4)), "<=", 11)


# Solve the model, if this return 0 an optimal solution is found
solve(trans_9_2)

sensitivity_table(trans_9_2)

```


# Problem 9.1-4  The Versatech Corporation

Plant      | Prod 1  |  Prod 2  | Prod 3  | Adjst Demand  | Capacity 
---------- | ------  |  ------- | ------- | -------       | -------     
1          | 31      | 45       | 38      | 0             | 400       
2          | 29      | 41       | 35      | 0             | 600       
3          | 32      | 46       | 40      | 0             | 400
4          | 28      | 42       | 1000    | 0             | 600
5          | 29      | 43       | 1000    | 0             | 1,000
Forecast   | 600     | 1,000    | 800     | 600           |
      
      
#### b. Set up and solve in R.  



```{r}

# Set up the cost minimization
trans_9_4 <- make.lp(0, 20)

# Build objective function and constraints
obj_fn <- c(31, 45, 38, 0, 
            29, 41, 35, 0, 
            32, 46, 40, 0,
            28, 42, 1000, 0,
            29, 43, 1000, 0)

matrix(obj_fn, nrow = 5, byrow=TRUE)
set.objfn(trans_9_4, obj_fn)


# Distribution Constraint
add.constraint(trans_9_4, c(rep(c(1, 0, 0, 0),5)), "=", 600)
add.constraint(trans_9_4, c(rep(c(0, 1, 0, 0),5)), "=", 1000)
add.constraint(trans_9_4, c(rep(c(0, 0, 1, 0),5)), "=", 800)
add.constraint(trans_9_4, c(rep(c(0, 0, 0, 1),5)), "=", 600)

# Plant Constraint
add.constraint(trans_9_4, c(rep(1, 4), rep(0, 16)), "<=", 400)
add.constraint(trans_9_4, c(rep(0, 4),rep(1, 4), rep(0, 12)), "<=", 600)
add.constraint(trans_9_4, c(rep(0, 8),rep(1, 4), rep(0, 8)), "<=", 400)
add.constraint(trans_9_4, c(rep(0, 12),rep(1, 4), rep(0, 4)), "<=", 600)
add.constraint(trans_9_4, c(rep(0, 16),rep(1, 4)), "<=", 1000)

# # Add names
# dimnames(trans_9_4) <- list(c("O", "A","B", "C", "D", "E", "T"), 
#                       c("OA", "OB", "OC", "AB", "AD", "BC", "BD", "BE", "CE", "DE", "DT", "ET"))

# Solve the model, if this return 0 an optimal solution is found
solve(trans_9_4)

sensitivity_table(trans_9_4)

```


# Problem 9.3-1  Assignee x Task

Assignee   | Task 1  |  Task 2  | Task 3  | Task 4 
---------- | ------  |  ------- | ------- | -------    
A          | 8       | 6        | 5       | 7             
B          | 6       | 5        | 3       | 4             
C          | 7       | 8        | 4       | 6       
D          | 6       | 7        | 5       | 6       
      
      
#### b. Set up and solve in R.  



```{r}

# Set up the cost minimization
trans_9_3_1 <- make.lp(0, 16)

# Build objective function and constraints
obj_fn <- c(8, 6, 5, 7,
            6, 5, 3, 4,
            7, 8, 4, 6, 
            6, 7, 5, 6)

matrix(obj_fn, nrow = 5, byrow=TRUE)
set.objfn(trans_9_3_1, obj_fn)

# Task Constraint
add.constraint(trans_9_3_1, c(rep(c(1, 0, 0, 0),4)), "=", 1)
add.constraint(trans_9_3_1, c(rep(c(0, 1, 0, 0),4)), "=", 1)
add.constraint(trans_9_3_1, c(rep(c(0, 0, 1, 0),4)), "=", 1)
add.constraint(trans_9_3_1, c(rep(c(0, 0, 0, 1),4)), "=", 1)

# Assignee Constraint
add.constraint(trans_9_3_1, c(rep(1, 4), rep(0, 12)), "=", 1)
add.constraint(trans_9_3_1, c(rep(0, 4),rep(1, 4), rep(0, 8)), "=", 1)
add.constraint(trans_9_3_1, c(rep(0, 8),rep(1, 4), rep(0, 4)), "=", 1)
add.constraint(trans_9_3_1, c(rep(0, 12),rep(1, 4)), "=", 1)


# Solve the model, if this return 0 an optimal solution is found
solve(trans_9_3_1)
sensitivity_table(trans_9_3_1)

```



# Problem 10.3-2 Trip to another town


Town   | A       |  B       | C       | D       |E       |Destination
-----  | ------  |  ------- | ------- | ------- |------- |-------     
Origin | 40      | 60       | 50      | ----    | ----   | ----            
A      |         | 10       | ----    | 70      | ----   | ----            
B      |         |          | 20      | 55      | 40     | ---- 
C      |         |          |         |         | 50     | ----
D      |         |          |         |         | 10     | 60
E      |         |          |         |         |        | 80
      
      
#### b. Set up and solve in R.  



```{r}

# Set up the cost minimization
shot_path_10_3_2 <- make.lp(0, 19)

# Build objective function and constraints
obj_fn <- c(40, 60, 50, # Origin
            10, 10, 70, 70,     # A
            20, 20, 55, 55, 40, 40, # B
            50, 50,         # C
            10, 10, 60,     # D
            80)         # E
            

set.objfn(shot_path_10_3_2, obj_fn)

# Edges Constraint                 OA,OB,OC,AB,BA,AD,DA,BC,CB,BD,DB,BE,EB,CE,EC,ED,DE,DT,ET
add.constraint(shot_path_10_3_2, c( 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 1) # Origin
add.constraint(shot_path_10_3_2, c(-1, 0, 0, 1,-1, 1,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 0) # A
add.constraint(shot_path_10_3_2, c( 0,-1, 0,-1, 1, 0, 0, 1,-1, 1,-1, 1,-1, 0, 0, 0, 0, 0, 0), "=", 0) # B
add.constraint(shot_path_10_3_2, c( 0, 0,-1, 0, 0, 0, 0,-1, 1, 0, 0, 0, 0, 1,-1, 0, 0, 0, 0), "=", 0) # C
add.constraint(shot_path_10_3_2, c( 0, 0, 0, 0, 0,-1, 1, 0, 0,-1, 1, 0, 0, 0, 0,-1, 1, 1, 0), "=", 0) # D
add.constraint(shot_path_10_3_2, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,-1, 1,-1, 1, 1,-1, 0, 1), "=", 0) # E
add.constraint(shot_path_10_3_2, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,-1,-1), "=", -1) # T

# Add names
dimnames(shot_path_10_3_2) <- list(c("O", "A","B", "C", "D", "E", "T"), 
                      c("OA", "OB", "OC", "AB", "BA", "AD", "DA", "BC", "CB", "BD", "DB", "BE", "EB", "CE", "EC", 
                        "DE", "ED", "DT", "ET"))


# Write to view the algebraic formulation
write.lp(shot_path_10_3_2, "shot_path_10_3_2.lp",type = 'lp')

# Solve the model
solve(shot_path_10_3_2)

sensitivity_table(shot_path_10_3_2)
```


# Problem 10.6-2 Flow from A to F


Town   | B       |  C       | D       | E       | F      
-----  | ------  |  ------- | ------- | ------- |-------      
A      | 9       | 7        | ----    | ----    | 20               
B      |         | ----     | 7       | 2       | ----               
C      |         |          | 4       | 6       | ----      
D      |         |          |         | 3       | 6     
E      |         |          |         |         | 9     
      
      
#### b. Set up and solve in R.  



```{r}

# Set up the cost minimization
shot_path_10_6_2 <- make.lp(0, 10)

# Build objective function and constraints
obj_fn <- c(9, 7, 20, # A
            7, 2,     # B
            4, 6,     # C
            3, 6,     # D
            9)        # E
            

set.objfn(shot_path_10_6_2, obj_fn)

# Edges Constraint
add.constraint(shot_path_10_6_2, c( 1, 1, 1, 0, 0, 0, 0, 0, 0, 0), "=", 1) # A
add.constraint(shot_path_10_6_2, c(-1, 0, 0, 1, 1, 0, 0, 0, 0, 0), "=", 0) # B
add.constraint(shot_path_10_6_2, c( 0,-1, 0, 0, 0, 1, 1, 0, 0, 0), "=", 0) # C
add.constraint(shot_path_10_6_2, c( 0, 0, 0,-1, 0,-1, 0, 1, 1, 0), "=", 0) # D
add.constraint(shot_path_10_6_2, c( 0, 0, 0, 0, 0, 0, 0,-1,-1,-1), "=", 0) # E
add.constraint(shot_path_10_6_2, c( 0, 0,-1, 0, 0, 0, 0, 0,-1,-1), "=",-1) # F

# Add names
dimnames(shot_path_10_6_2) <- list(c("A","B", "C", "D", "E", "F"), 
                      c("AB", "AC", "AF", "BD", "BE", "CD", "CE", "DE", "DF", "EF"))


# Write to view the algebraic formulation
write.lp(shot_path_10_6_2, "shot_path_10_6_2.lp",type = 'lp')

# Solve the model
solve(shot_path_10_6_2)

sensitivity_table(shot_path_10_6_2)
```



